### ISSUE TITLE
Paperclip::Errors::InfiniteInterpolationError

### ISSUE THREAD

**Issue by lucasgerard** [GoGoCarl/paperclip-cloudinary#1] opened 2016-05-06 13:33 UTC
Hi,

I'm currently using Paperclip with s3 storage, and changing default settings to cloudinary storage - following paperclip-cloudinary readme - leads to the error below. Any idea where to go from here?

Thanks!

`Paperclip::Errors::InfiniteInterpolationError - Paperclip::Errors::InfiniteInterpolationError:
   () Users/lucas/.rvm/gems/ruby-2.2.2/bundler/gems/paperclip-97c78efdce65/lib/paperclip/interpolations.rb:53:in`url'
   () Users/lucas/.rvm/gems/ruby-2.2.2/bundler/gems/paperclip-97c78efdce65/lib/paperclip/interpolations.rb:34:in `block (2 levels) in interpolate'
   () Users/lucas/.rvm/gems/ruby-2.2.2/bundler/gems/paperclip-97c78efdce65/lib/paperclip/interpolations.rb:33:in`block in interpolate'
   () Users/lucas/.rvm/gems/ruby-2.2.2/bundler/gems/paperclip-97c78efdce65/lib/paperclip/interpolations.rb:32:in `interpolate'
   () Users/lucas/.rvm/gems/ruby-2.2.2/bundler/gems/paperclip-97c78efdce65/lib/paperclip/attachment.rb:544:in`interpolate'
   () Users/lucas/.rvm/gems/ruby-2.2.2/bundler/gems/paperclip-97c78efdce65/lib/paperclip/attachment.rb:166:in `path'
  paperclip-cloudinary (1.1.0) lib/paperclip/storage/cloudinary.rb:71:in`url'`

**Comment by GoGoCarl** [comment] 2016-05-06 16:38
Hi @lucasgerard,

Would you care to post the relevant section of the offending `has_attached_file` declaration?  Sometimes this can occur when you specify a `url` parameter that contains `:url`.

Thanks for reporting this.

**Comment by lucasgerard** [comment] 2016-05-06 18:20
Hi @GoGoCarl thanks for your reply. Here is the declaration on my Actuality class:

```
has_attached_file :picture,
    :styles => { medium: '300x300>', thumb: '100x100>', landscape: '1800x1200#'},
    :storage => :cloudinary
```

The error is actually raised as `.url` is called, e.g. : `a.picture.url(:landscape)`.

Previous objects have pictures stored on s3, might it be a compatibility issue with s3 storage?

**Comment by GoGoCarl** [comment] 2016-05-06 18:39
Yes, that would make sense.  I know that specifically with s3 storage, there was an issue with getting `Paperclip::Errors::InfiniteInterpolationError`s when no `path` option was specified and the default `url` option was used.

So, one thing to look for would be what you are using for your default `url` option for Paperclip attachments. In many configurations, this information is spelled out in an initializer, such as `config/initializers/paperclip.rb`.

Also, something you can do to verify this being the issue (and probably a short-term fix) would be to specify the `path` option on `has_attached_file`, i.e:

```
has_attached_file :picture,
  :styles => { medium: '300x300>', thumb: '100x100>', landscape: '1800x1200#'},
  :storage => :cloudinary,
  :path => "/:class/:attachment/:id_partition/:style/:filename"
```

The path given here is just an example.  Your desired path is probably in an initializer file; but you can spell this out to prevent the error.  If providing the path stops the error, then you have found your issue.  If not, then it's possible the `path`, not just the `url`, is the cause.  But most likely, given what I've read about this issue with s3 specifically, providing the `path` should help.

**Comment by lucasgerard** [comment] 2016-05-09 09:07
Hi,

Thank you for the hint, I'm no longer having the error, but as my previous objects have attachments stored in s3, I had to keep s3 settings to read their url and here is my new settings:

paperclib.rb :

```
defaults = {
 storage: :cloudinary,
 s3_credentials: {
   bucket: ENV['S3_BUCKET_NAME'],
   access_key_id: ENV['AWS_ACCESS_KEY_ID'],
   secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
 },
 s3_protocol: ENV['MAILER_PROTOCOL'].to_sym,
 url: ':s3_domain_url',
 path: '/:rails_env/:class/:attachment/:hash.:extension',
 hash_secret: ENV['AWS_SECRET_ACCESS_KEY']
}

defaults.each do |key, value|
 Paperclip::Attachment.default_options[key] = value
end
```

and actuality.rb :

```
has_attached_file :picture,
    convert_options: { :all => "-quality 75" },
    styles: { medium: '300x300>', thumb: '100x100>', landscape: '1800x1200#'},
    processors: [:thumbnail, :compression]
```

However, as I try to upload a picture using `f.input :picture, :as => :file ,` I get the following error. Any idea where to go from here?
(I've included the gem, ran `bundle install` and have downloaded the cloudinary.yml config file under /config.)

**Errno::ECONNREFUSED - Connection refused - connect(2) for nil port 80:**
   () Users/lucas/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
   () Users/lucas/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:74:in`timeout'
   () Users/lucas/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:878:in `connect'
   () Users/lucas/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:863:in`do_start'
   () Users/lucas/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:852:in `start'
  rest-client (1.8.0) lib/restclient/request.rb:413:in`transmit'
  rest-client (1.8.0) lib/restclient/request.rb:176:in `execute'
  rest-client (1.8.0) lib/restclient/request.rb:41:in`execute'
  cloudinary (1.1.6) lib/cloudinary/uploader.rb:152:in `exists?'
  paperclip-cloudinary (1.1.0) lib/paperclip/storage/cloudinary.rb:61:in`exists?'
   () Users/lucas/.rvm/gems/ruby-2.2.2/bundler/gems/paperclip-97c78efdce65/lib/paperclip/attachment.rb:557:in `block in queue_all_for_delete'
   () Users/lucas/.rvm/gems/ruby-2.2.2/bundler/gems/paperclip-97c78efdce65/lib/paperclip/attachment.rb:556:in`queue_all_for_delete'
   () Users/lucas/.rvm/gems/ruby-2.2.2/bundler/gems/paperclip-97c78efdce65/lib/paperclip/attachment.rb:250:in `clear'
   () Users/lucas/.rvm/gems/ruby-2.2.2/bundler/gems/paperclip-97c78efdce65/lib/paperclip/attachment.rb:102:in`assign'
   () Users/lucas/.rvm/gems/ruby-2.2.2/bundler/gems/paperclip-97c78efdce65/lib/paperclip/has_attached_file.rb:66:in `block in define_setter'

**Comment by GoGoCarl** [comment] 2016-05-09 13:51
Hmm, it looks like you have an interesting use case. I'd like to know more about, in general, what you're trying to accomplish with your setup. Are you trying to sort of "silently" migrate to Cloudinary, but maintain a sort of bridge of compatibility with both (i.e. existing s3 images appear but new uploads go to Cloudinary)?

Looking at your default configuration, since the `:storage` option is set to `:cloudinary`, the s3 storage is essentially turned off here, so objects won't be able to read things like `: s3_credentials` and `:s3_protocol` unless they, override `:storage` on their `has_attached_file` and set it to `:s3`.  Hence, conversely, setting the Cloudinary storage's `:url` option to `:s3_domain_url` won't really work here because Cloudinary is not sure what to do with that information, since it is specific to your s3 storage mechanism, which is completely separate from Cloudinary.

This would explain "Connection refused - connect(2) for nil port 80:", as `:s3_domain_url` is resolving to nothing (`nil`), and the url of `nil` can't be reached.

Anyway, let me know more about the goals of your set up here and I can offer some directional suggestions.

**Comment by GoGoCarl** [comment] 2016-12-15 01:19
Closed due to inactivity.

**Closed as completed by GoGoCarl** 2016-12-15 01:19 UTC
